---

# Run Docker compose to activate web frontend and web backend
- name: Run docker compose
  become: yes
  docker_compose:
    project_src: "/home/ubuntu/COMP90024A2/COMP90024-Assignment2/web/"
    pull: false
    build: yes
    state: present
    remove_orphans: yes
    recreate: always
