version: '3'
services:
  frontend:
    build: 
      context: .
    volumes:
      - .:/frontend
    ports:
      - 5000:5000
    image: frontend
    container_name: react_container
    command: npm start