---
# Build Docker image for tweepy

- name: Build an image and push it to local repo _realtime
  docker_image:
    build:
      path: "/home/ubuntu/COMP90024/COMP90024-Assignment2/tweepy"
      pull: yes
    name: tweepy
    tag: latest
    source: build
    force: yes
  become: yes
  environment: "{{ proxy_env }}"

# Stop existing Docker containers for Twitter Harvesters and remove them (if any)
- name: Stop tweepy Docker container
  become: yes
  docker_container:
    name: tweepy
    state: absent

# Create new docker container for Crawler and start container
- name: Create and start tweepy Docker container
  become: yes
  docker_container:
    name: tweepy
    image: tweepy
    state: started
    pull: false
    recreate: true
    restart_policy: always

