---
ansible_user: ubuntu
working_directory: /home/ubuntu/COMP90024A2
git_rep: /home/ubuntu/COMP90024A2/gitRepor
ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
ansible_ssh_key: "config/SSH.pem"

couchdb_image: ibmcom/couchdb3:latest
couchdb_user: admin
couchdb_pass: admin
couchdb_VERSION: "3.2.1"
couchdb_cookie: "a192aeb9904e6590849337933b000c99"
cluster_name: "_cluster_setup"
couchdb_container_name: "couchdb_"
couchdb_port: 5984

proxy_env:
  HTTP_PROXY: http://wwwproxy.unimelb.edu.au:8000/
  HTTPS_PROXY: http://wwwproxy.unimelb.edu.au:8000/
  http_proxy: http://wwwproxy.unimelb.edu.au:8000/
  https_proxy: http://wwwproxy.unimelb.edu.au:8000/
  no_proxy: localhost, 127.0.0.1, localaddress, 172.16.0.0/12, .melbourne.rc.nectar.org.au, .storage.unimelb.edu.au, .cloud.unimelb.edu.au

volumes:
  - device: /dev/vdb
    mountpoint: /data