---

- name: Delete remote working directory if exists
  file:
    state: absent
    path: '{{ remote_working_directory }}'

- name: Creates remote working directory
  file:
    path: '{{ remote_working_directory }}'
    state: directory
    mode: 0755

- name: git clone
  shell: git clone https://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@github.com/duyifei1999/COMP90024-Assignment2.git
  args:
    chdir: '{{ remote_working_directory }}'
