---
# Deploy servers
- hosts: dbServers
  vars_files:
    - host_vars/config.yaml
  gather_facts: true
  roles:
    - role: install-couchdb

- hosts: dbMaster
  vars_files:
    - host_vars/config.yaml
  gather_facts: true
  roles:
    - role: setup-couchdb-clusters

- hosts: instance2
  vars_files:
    - host_vars/config.yaml
  gather_facts: true
  roles:
    - role: tweepy-housing-setup

- hosts: instance3
  vars_files:
    - host_vars/config.yaml
  gather_facts: true
  roles:
    - role: tweepy-language-setup
    
- hosts: webserver
  vars_files:
    - host_vars/config.yaml
  gather_facts: true
  roles:
    - role: web-setup



